# Generated by Django 4.1.3 on 2022-12-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0003_alter_dpr_table_oa_commercial_traffic_put_on_air_ms1_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dpr_table',
            constraint=models.UniqueConstraint(fields=('SITE_ID', 'BAND'), name='unique_SITE_ID'),
        ),
    ]
