# Generated by Django 4.1.3 on 2022-12-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0006_dpr_table1_soft_at_acceptance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpr_table1',
            name='PERFORMANCE_AT_ACCEPTANCE_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpr_table1',
            name='PERFORMANCE_AT_ACCEPTANCE_MAIL',
            field=models.FileField(blank=True, null=True, upload_to='dpr_acceptance_mail/'),
        ),
        migrations.AddField(
            model_name='dpr_table1',
            name='PERFORMANCE_AT_OFFERED_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpr_table1',
            name='PERFORMANCE_AT_OFFERED_REMARKS',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dpr_table1',
            name='PERFORMANCE_AT_PENDING_REASON',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dpr_table1',
            name='PERFORMANCE_AT_PENDING_REMARK',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dpr_table1',
            name='PERFORMANCE_AT_PENDING_TAT_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpr_table1',
            name='PERFORMANCE_AT_REJECTED_TAT_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpr_table1',
            name='PERFORMANCE_AT_REJECTION_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpr_table1',
            name='PERFORMANCE_AT_REJECTION_REASON',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dpr_table1',
            name='PHYSICAL_AT_ACCEPTANCE_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpr_table1',
            name='PHYSICAL_AT_ACCEPTANCE_MAIL',
            field=models.FileField(blank=True, null=True, upload_to='dpr_acceptance_mail/'),
        ),
        migrations.AddField(
            model_name='dpr_table1',
            name='PHYSICAL_AT_OFFERED_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpr_table1',
            name='PHYSICAL_AT_OFFERED_REMARKS',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dpr_table1',
            name='PHYSICAL_AT_PENDING_REASON',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dpr_table1',
            name='PHYSICAL_AT_PENDING_REMARK',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dpr_table1',
            name='PHYSICAL_AT_PENDING_TAT_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpr_table1',
            name='PHYSICAL_AT_REJECTED_TAT_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpr_table1',
            name='PHYSICAL_AT_REJECTION_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpr_table1',
            name='PHYSICAL_AT_REJECTION_REASON',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
