# Generated by Django 4.1.3 on 2022-12-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0009_alter_dpr_table1_physical_at_acceptance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpr_table1',
            name='uploaded_date',
        ),
    ]
