# Generated by Django 4.1.3 on 2022-12-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0015_rename_at_status_performance_at_performance_at_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='performance_at',
            new_name='performance_at_table',
        ),
    ]
