# Generated by Django 4.1.3 on 2022-12-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0016_rename_performance_at_performance_at_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance_at_table',
            name='Performance_AT_Status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
